"""
HARVEX Crop Knowledge Catalog v3
Canonical crop database for the intelligent crop recommendation engine.

Architecture:
- CROP_CATALOG: full registry with bilingual names, agronomic requirements
- Every crop has: crop_id, name_en, name_te, category, soil/climate/water requirements
- Sources: ICAR, FAO, State Agricultural Universities (ANGRAU, PJTSAU)
- The catalog is expandable but every crop must have agronomic provenance.

IMPORTANT: This catalog is used by the NEW intelligent recommendation engine.
The existing crop_knowledge.py is preserved for the legacy ML-based endpoint.
"""

from typing import Dict, List, Optional, Any, Tuple

# =============================================================================
# CANONICAL CROP CATALOG
# =============================================================================

CROP_CATALOG: Dict[str, Dict[str, Any]] = {
    # ===== CEREALS =====
    "rice": {
        "crop_id": "rice",
        "name_en": "Rice",
        "name_te": "\u0c35\u0c30\u0c3f",
        "category": "Cereals",
        "scientific_name": "Oryza sativa",
        "soil_requirements": {
            "soil_types": ["clay", "loamy", "alluvial"],
            "ph_range": [5.5, 7.0],
            "drainage": "poor_to_moderate",
        },
        "climate_requirements": {
            "temp_range": [20, 35],
            "optimal_temp": 27,
            "humidity_range": [60, 90],
            "rainfall_mm": [1000, 2000],
        },
        "water_requirement": "high",
        "irrigation_compatibility": ["flood", "sprinkler", "drip"],
        "season_suitability": {"kharif": 0.95, "rabi": 0.3, "summer": 0.2},
        "growth_duration_days": [120, 150],
        "risk_factors": ["flood", "blast", "drought_sensitivity"],
        "source": "ICAR-Indian Institute of Rice Research",
        "source_version": "v1.0",
    },
    "maize": {
        "crop_id": "maize",
        "name_en": "Maize",
        "name_te": "\u0c2e\u0c4a\u0c1c\u0c40",
        "category": "Cereals",
        "scientific_name": "Zea mays",
        "soil_requirements": {
            "soil_types": ["loamy", "sandy_loam", "alluvial"],
            "ph_range": [5.5, 7.5],
            "drainage": "well_drained",
        },
        "climate_requirements": {
            "temp_range": [18, 32],
            "optimal_temp": 25,
            "humidity_range": [50, 80],
            "rainfall_mm": [500, 800],
        },
        "water_requirement": "medium",
        "irrigation_compatibility": ["drip", "sprinkler", "flood"],
        "season_suitability": {"kharif": 0.9, "rabi": 0.7, "summer": 0.5},
        "growth_duration_days": [80, 120],
        "risk_factors": ["waterlogging", "fall_armyworm"],
        "source": "ICAR-Indian Institute of Maize Research",
        "source_version": "v1.0",
    },
    "wheat": {
        "crop_id": "wheat",
        "name_en": "Wheat",
        "name_te": "\u0c17\u0c4b\u0c27\u0c41\u0c2e",
        "category": "Cereals",
        "scientific_name": "Triticum aestivum",
        "soil_requirements": {
            "soil_types": ["loamy", "clay_loam", "alluvial"],
            "ph_range": [6.0, 7.5],
            "drainage": "well_drained",
        },
        "climate_requirements": {
            "temp_range": [10, 25],
            "optimal_temp": 20,
            "humidity_range": [40, 70],
            "rainfall_mm": [400, 800],
        },
        "water_requirement": "medium",
        "irrigation_compatibility": ["flood", "sprinkler", "drip"],
        "season_suitability": {"kharif": 0.1, "rabi": 0.95, "summer": 0.05},
        "growth_duration_days": [120, 150],
        "risk_factors": ["rust", "heat_stress", "terminal_heat"],
        "source": "ICAR-Indian Wheat and Barley Research Institute",
        "source_version": "v1.0",
    },
    "sorghum": {
        "crop_id": "sorghum",
        "name_en": "Sorghum",
        "name_te": "\u0c1c\u0c4a\u0c35\u0c30",
        "category": "Cereals",
        "scientific_name": "Sorghum bicolor",
        "soil_requirements": {
            "soil_types": ["loamy", "clay_loam", "black"],
            "ph_range": [6.0, 8.0],
            "drainage": "moderate",
        },
        "climate_requirements": {
            "temp_range": [20, 38],
            "optimal_temp": 30,
            "humidity_range": [30, 60],
            "rainfall_mm": [400, 700],
        },
        "water_requirement": "low",
        "irrigation_compatibility": ["rainfed", "drip", "sprinkler"],
        "season_suitability": {"kharif": 0.9, "rabi": 0.3, "summer": 0.1},
        "growth_duration_days": [90, 120],
        "risk_factors": ["striga", "stem_borer"],
        "source": "ICAR-Sorghum Research Institute",
        "source_version": "v1.0",
    },
    "pearl_millet": {
        "crop_id": "pearl_millet",
        "name_en": "Pearl Millet",
        "name_te": "\u0c38\u0c30\u0c4d\u0c35",
        "category": "Millets",
        "scientific_name": "Pennisetum glaucum",
        "soil_requirements": {
            "soil_types": ["sandy", "loamy", "sandy_loam"],
            "ph_range": [6.0, 8.0],
            "drainage": "well_drained",
        },
        "climate_requirements": {
            "temp_range": [20, 38],
            "optimal_temp": 30,
            "humidity_range": [30, 60],
            "rainfall_mm": [250, 500],
        },
        "water_requirement": "very_low",
        "irrigation_compatibility": ["rainfed", "drip"],
        "season_suitability": {"kharif": 0.95, "rabi": 0.2, "summer": 0.1},
        "growth_duration_days": [60, 90],
        "risk_factors": ["downy_mildew", "blast"],
        "source": "ICAR-Millet Research Institute",
        "source_version": "v1.0",
    },
    "finger_millet": {
        "crop_id": "finger_millet",
        "name_en": "Finger Millet",
        "name_te": "\u0c30\u0c3e\u0c17\u0c3f",
        "category": "Millets",
        "scientific_name": "Eleusine coracana",
        "soil_requirements": {
            "soil_types": ["loamy", "clay_loam", "black"],
            "ph_range": [5.0, 8.0],
            "drainage": "moderate",
        },
        "climate_requirements": {
            "temp_range": [15, 35],
            "optimal_temp": 25,
            "humidity_range": [40, 75],
            "rainfall_mm": [400, 1000],
        },
        "water_requirement": "low",
        "irrigation_compatibility": ["rainfed", "drip", "sprinkler"],
        "season_suitability": {"kharif": 0.9, "rabi": 0.5, "summer": 0.2},
        "growth_duration_days": [90, 120],
        "risk_factors": ["blast", "brown_leaf_spot"],
        "source": "ICAR-Millet Research Institute",
        "source_version": "v1.0",
    },

    # ===== PULSES =====
    "chickpea": {
        "crop_id": "chickpea",
        "name_en": "Chickpea",
        "name_te": "\u0c36\u0c46\u0c28\u0c17",
        "category": "Pulses",
        "scientific_name": "Cicer arietinum",
        "soil_requirements": {
            "soil_types": ["loamy", "clay_loam", "black"],
            "ph_range": [6.0, 8.0],
            "drainage": "well_drained",
        },
        "climate_requirements": {
            "temp_range": [15, 30],
            "optimal_temp": 22,
            "humidity_range": [40, 70],
            "rainfall_mm": [400, 600],
        },
        "water_requirement": "low",
        "irrigation_compatibility": ["rainfed", "drip", "sprinkler"],
        "season_suitability": {"kharif": 0.2, "rabi": 0.95, "summer": 0.1},
        "growth_duration_days": [90, 120],
        "risk_factors": ["wilt", "root_rot", "botrytis"],
        "source": "ICAR-Indian Institute of Pulses Research",
        "source_version": "v1.0",
    },
    "pigeon_pea": {
        "crop_id": "pigeon_pea",
        "name_en": "Pigeon Pea",
        "name_te": "\u0c15\u0c3e\u0c27\u0c3f\u0c32\u0c47\u0c28\u0c3f\u0c15",
        "category": "Pulses",
        "scientific_name": "Cajanus cajan",
        "soil_requirements": {
            "soil_types": ["loamy", "clay_loam", "black"],
            "ph_range": [6.0, 7.5],
            "drainage": "moderate",
        },
        "climate_requirements": {
            "temp_range": [18, 35],
            "optimal_temp": 28,
            "humidity_range": [40, 70],
            "rainfall_mm": [400, 700],
        },
        "water_requirement": "low",
        "irrigation_compatibility": ["rainfed", "drip"],
        "season_suitability": {"kharif": 0.9, "rabi": 0.4, "summer": 0.1},
        "growth_duration_days": [150, 210],
        "risk_factors": ["wilt", "phytophthora"],
        "source": "ICAR-Indian Institute of Pulses Research",
        "source_version": "v1.0",
    },
    "green_gram": {
        "crop_id": "green_gram",
        "name_en": "Green Gram",
        "name_te": "\u0c2a\u0c1a\u0c4d\u0c1a\u0c40\u0c32",
        "category": "Pulses",
        "scientific_name": "Vigna radiata",
        "soil_requirements": {
            "soil_types": ["loamy", "sandy_loam", "alluvial"],
            "ph_range": [6.2, 7.5],
            "drainage": "well_drained",
        },
        "climate_requirements": {
            "temp_range": [18, 35],
            "optimal_temp": 28,
            "humidity_range": [50, 75],
            "rainfall_mm": [300, 600],
        },
        "water_requirement": "low",
        "irrigation_compatibility": ["rainfed", "drip"],
        "season_suitability": {"kharif": 0.8, "rabi": 0.7, "summer": 0.5},
        "growth_duration_days": [60, 75],
        "risk_factors": ["yellow_mosaic_virus", "cercospora"],
        "source": "ICAR-Indian Institute of Pulses Research",
        "source_version": "v1.0",
    },
    "black_gram": {
        "crop_id": "black_gram",
        "name_en": "Black Gram",
        "name_te": "\u0c2e\u0c3f\u0c28\u0c21\u0c41",
        "category": "Pulses",
        "scientific_name": "Vigna mungo",
        "soil_requirements": {
            "soil_types": ["loamy", "clay_loam", "black"],
            "ph_range": [6.0, 7.5],
            "drainage": "moderate",
        },
        "climate_requirements": {
            "temp_range": [20, 35],
            "optimal_temp": 28,
            "humidity_range": [50, 80],
            "rainfall_mm": [400, 700],
        },
        "water_requirement": "low",
        "irrigation_compatibility": ["rainfed", "drip"],
        "season_suitability": {"kharif": 0.85, "rabi": 0.6, "summer": 0.3},
        "growth_duration_days": [70, 90],
        "risk_factors": ["yellow_mosaic_virus", "root_rot"],
        "source": "ICAR-Indian Institute of Pulses Research",
        "source_version": "v1.0",
    },
    "lentil": {
        "crop_id": "lentil",
        "name_en": "Lentil",
        "name_te": "\u0c2e\u0c38\u0c41\u0c30",
        "category": "Pulses",
        "scientific_name": "Lens culinaris",
        "soil_requirements": {
            "soil_types": ["loamy", "sandy_loam", "alluvial"],
            "ph_range": [6.0, 8.0],
            "drainage": "well_drained",
        },
        "climate_requirements": {
            "temp_range": [12, 25],
            "optimal_temp": 20,
            "humidity_range": [40, 65],
            "rainfall_mm": [300, 500],
        },
        "water_requirement": "low",
        "irrigation_compatibility": ["rainfed", "drip"],
        "season_suitability": {"kharif": 0.1, "rabi": 0.95, "summer": 0.05},
        "growth_duration_days": [90, 120],
        "risk_factors": ["wilt", "botrytis_gray_mold"],
        "source": "ICAR-Indian Institute of Pulses Research",
        "source_version": "v1.0",
    },

    # ===== OILSEEDS =====
    "groundnut": {
        "crop_id": "groundnut",
        "name_en": "Groundnut",
        "name_te": "\u0c35\u0c47\u0c30\u0c41\u0c36\u0c28\u0c17",
        "category": "Oilseeds",
        "scientific_name": "Arachis hypogaea",
        "soil_requirements": {
            "soil_types": ["sandy_loam", "loamy", "red"],
            "ph_range": [6.0, 7.0],
            "drainage": "well_drained",
        },
        "climate_requirements": {
            "temp_range": [20, 35],
            "optimal_temp": 28,
            "humidity_range": [40, 70],
            "rainfall_mm": [400, 800],
        },
        "water_requirement": "medium",
        "irrigation_compatibility": ["drip", "sprinkler", "flood"],
        "season_suitability": {"kharif": 0.7, "rabi": 0.85, "summer": 0.3},
        "growth_duration_days": [90, 120],
        "risk_factors": ["late_leaf_spot", "aflatoxin"],
        "source": "ICAR-Directorate of Groundnut Research",
        "source_version": "v1.0",
    },
    "soybean": {
        "crop_id": "soybean",
        "name_en": "Soybean",
        "name_te": "\u0c38\u0c4b\u0c2f\u0c3e\u0c2c\u0c40\u0c28\u0c4d",
        "category": "Oilseeds",
        "scientific_name": "Glycine max",
        "soil_requirements": {
            "soil_types": ["loamy", "clay_loam", "black"],
            "ph_range": [6.0, 7.5],
            "drainage": "well_drained",
        },
        "climate_requirements": {
            "temp_range": [20, 35],
            "optimal_temp": 28,
            "humidity_range": [50, 80],
            "rainfall_mm": [500, 900],
        },
        "water_requirement": "medium",
        "irrigation_compatibility": ["drip", "sprinkler", "rainfed"],
        "season_suitability": {"kharif": 0.95, "rabi": 0.1, "summer": 0.05},
        "growth_duration_days": [90, 120],
        "risk_factors": ["gall_midge", "stem_borer"],
        "source": "ICAR-Indian Institute of Soybean Research",
        "source_version": "v1.0",
    },
    "sunflower": {
        "crop_id": "sunflower",
        "name_en": "Sunflower",
        "name_te": "\u0c38\u0c42\u0c30\u0c4d\u0c2f\u0c3e\u0c2e\u0c41\u0c16\u0c40",
        "category": "Oilseeds",
        "scientific_name": "Helianthus annuus",
        "soil_requirements": {
            "soil_types": ["loamy", "sandy_loam", "alluvial"],
            "ph_range": [6.0, 7.5],
            "drainage": "well_drained",
        },
        "climate_requirements": {
            "temp_range": [18, 33],
            "optimal_temp": 25,
            "humidity_range": [40, 70],
            "rainfall_mm": [400, 700],
        },
        "water_requirement": "medium",
        "irrigation_compatibility": ["drip", "sprinkler", "rainfed"],
        "season_suitability": {"kharif": 0.6, "rabi": 0.8, "summer": 0.5},
        "growth_duration_days": [80, 100],
        "risk_factors": ["rust", "downy_mildew"],
        "source": "ICAR-Directorate of Oilseeds Research",
        "source_version": "v1.0",
    },
    "sesame": {
        "crop_id": "sesame",
        "name_en": "Sesame",
        "name_te": "\u0c28\u0c41\u0c35\u0c4d\u0c35",
        "category": "Oilseeds",
        "scientific_name": "Sesamum indicum",
        "soil_requirements": {
            "soil_types": ["loamy", "sandy_loam", "alluvial"],
            "ph_range": [5.5, 8.0],
            "drainage": "well_drained",
        },
        "climate_requirements": {
            "temp_range": [22, 38],
            "optimal_temp": 30,
            "humidity_range": [30, 60],
            "rainfall_mm": [300, 600],
        },
        "water_requirement": "low",
        "irrigation_compatibility": ["rainfed", "drip"],
        "season_suitability": {"kharif": 0.7, "rabi": 0.5, "summer": 0.4},
        "growth_duration_days": [70, 90],
        "risk_factors": ["web_blower", "root_rot"],
        "source": "ICAR-Directorate of Oilseeds Research",
        "source_version": "v1.0",
    },
    "mustard": {
        "crop_id": "mustard",
        "name_en": "Mustard",
        "name_te": "\u0c06\u0c35\u0c3f\u0c36\u0c3f\u0c2f\u0c2e\u0c41",
        "category": "Oilseeds",
        "scientific_name": "Brassica juncea",
        "soil_requirements": {
            "soil_types": ["loamy", "clay_loam", "sandy_loam"],
            "ph_range": [6.0, 7.5],
            "drainage": "well_drained",
        },
        "climate_requirements": {
            "temp_range": [10, 25],
            "optimal_temp": 20,
            "humidity_range": [40, 70],
            "rainfall_mm": [300, 600],
        },
        "water_requirement": "low",
        "irrigation_compatibility": ["rainfed", "drip", "sprinkler"],
        "season_suitability": {"kharif": 0.1, "rabi": 0.95, "summer": 0.05},
        "growth_duration_days": [110, 140],
        "risk_factors": ["white_rust", "aphid"],
        "source": "ICAR-Directorate of Rapeseed-Mustard Research",
        "source_version": "v1.0",
    },

    # ===== VEGETABLES =====
    "tomato": {
        "crop_id": "tomato",
        "name_en": "Tomato",
        "name_te": "\u0c1f\u0c2e\u0c3e\u0c1f\u0c3e",
        "category": "Vegetables",
        "scientific_name": "Solanum lycopersicum",
        "soil_requirements": {
            "soil_types": ["loamy", "sandy_loam", "alluvial"],
            "ph_range": [6.0, 7.0],
            "drainage": "well_drained",
        },
        "climate_requirements": {
            "temp_range": [18, 30],
            "optimal_temp": 25,
            "humidity_range": [50, 75],
            "rainfall_mm": [600, 1000],
        },
        "water_requirement": "medium",
        "irrigation_compatibility": ["drip", "sprinkler", "flood"],
        "season_suitability": {"kharif": 0.7, "rabi": 0.85, "summer": 0.5},
        "growth_duration_days": [60, 80],
        "risk_factors": ["late_blight", "bacterial_wilt", "fruit_borer"],
        "source": "ICAR-IIHR Bangalore",
        "source_version": "v1.0",
    },
    "onion": {
        "crop_id": "onion",
        "name_en": "Onion",
        "name_te": "\u0c09\u0c32\u0c4d\u0c32\u0c3f",
        "category": "Vegetables",
        "scientific_name": "Allium cepa",
        "soil_requirements": {
            "soil_types": ["loamy", "sandy_loam", "alluvial"],
            "ph_range": [6.0, 7.0],
            "drainage": "well_drained",
        },
        "climate_requirements": {
            "temp_range": [13, 33],
            "optimal_temp": 25,
            "humidity_range": [50, 70],
            "rainfall_mm": [500, 800],
        },
        "water_requirement": "medium",
        "irrigation_compatibility": ["drip", "sprinkler", "flood"],
        "season_suitability": {"kharif": 0.6, "rabi": 0.85, "summer": 0.4},
        "growth_duration_days": [80, 120],
        "risk_factors": ["purple_blotch", "thrips", "neck_rot"],
        "source": "ICAR-IIHR Bangalore",
        "source_version": "v1.0",
    },
    "potato": {
        "crop_id": "potato",
        "name_en": "Potato",
        "name_te": "\u0c06\u0c32\u0c41",
        "category": "Vegetables",
        "scientific_name": "Solanum tuberosum",
        "soil_requirements": {
            "soil_types": ["sandy_loam", "loamy", "alluvial"],
            "ph_range": [5.0, 6.5],
            "drainage": "well_drained",
        },
        "climate_requirements": {
            "temp_range": [15, 25],
            "optimal_temp": 20,
            "humidity_range": [60, 80],
            "rainfall_mm": [500, 800],
        },
        "water_requirement": "medium",
        "irrigation_compatibility": ["drip", "sprinkler", "flood"],
        "season_suitability": {"kharif": 0.2, "rabi": 0.95, "summer": 0.1},
        "growth_duration_days": [80, 120],
        "risk_factors": ["late_blight", "early_blight", "wilt"],
        "source": "ICAR-Central Potato Research Institute",
        "source_version": "v1.0",
    },
    "okra": {
        "crop_id": "okra",
        "name_en": "Okra",
        "name_te": "\u0c2c\u0c46\u0c02\u0d21",
        "category": "Vegetables",
        "scientific_name": "Abelmoschus esculentus",
        "soil_requirements": {
            "soil_types": ["loamy", "sandy_loam", "alluvial"],
            "ph_range": [6.0, 7.5],
            "drainage": "well_drained",
        },
        "climate_requirements": {
            "temp_range": [22, 35],
            "optimal_temp": 28,
            "humidity_range": [50, 80],
            "rainfall_mm": [500, 800],
        },
        "water_requirement": "medium",
        "irrigation_compatibility": ["drip", "sprinkler", "flood"],
        "season_suitability": {"kharif": 0.8, "rabi": 0.3, "summer": 0.6},
        "growth_duration_days": [50, 65],
        "risk_factors": ["fruit_borer", "yellow_mosaic"],
        "source": "ICAR-IIHR Bangalore",
        "source_version": "v1.0",
    },
    "brinjal": {
        "crop_id": "brinjal",
        "name_en": "Brinjal",
        "name_te": "\u0c35\u0c3e\u0c15\u0c3e\u0c2f",
        "category": "Vegetables",
        "scientific_name": "Solanum melongena",
        "soil_requirements": {
            "soil_types": ["loamy", "clay_loam", "alluvial"],
            "ph_range": [5.5, 7.0],
            "drainage": "moderate",
        },
        "climate_requirements": {
            "temp_range": [20, 35],
            "optimal_temp": 28,
            "humidity_range": [50, 75],
            "rainfall_mm": [600, 1000],
        },
        "water_requirement": "medium",
        "irrigation_compatibility": ["drip", "sprinkler", "flood"],
        "season_suitability": {"kharif": 0.7, "rabi": 0.8, "summer": 0.5},
        "growth_duration_days": [60, 80],
        "risk_factors": ["fruit_borer", "wilt", "little_leaf"],
        "source": "ICAR-IIHR Bangalore",
        "source_version": "v1.0",
    },
    "cabbage": {
        "crop_id": "cabbage",
        "name_en": "Cabbage",
        "name_te": "\u0c1c\u0c3e\u0c21",
        "category": "Vegetables",
        "scientific_name": "Brassica oleracea var. capitata",
        "soil_requirements": {
            "soil_types": ["loamy", "clay_loam", "alluvial"],
            "ph_range": [6.0, 7.5],
            "drainage": "well_drained",
        },
        "climate_requirements": {
            "temp_range": [10, 25],
            "optimal_temp": 18,
            "humidity_range": [50, 75],
            "rainfall_mm": [500, 800],
        },
        "water_requirement": "medium",
        "irrigation_compatibility": ["drip", "sprinkler", "flood"],
        "season_suitability": {"kharif": 0.2, "rabi": 0.95, "summer": 0.1},
        "growth_duration_days": [60, 90],
        "risk_factors": ["diamondback_moth", "black_rot"],
        "source": "ICAR-IIHR Bangalore",
        "source_version": "v1.0",
    },

    # ===== FRUITS =====
    "banana": {
        "crop_id": "banana",
        "name_en": "Banana",
        "name_te": "\u0c05\u0c30\u0c1f\u0c3f",
        "category": "Fruits",
        "scientific_name": "Musa spp.",
        "soil_requirements": {
            "soil_types": ["loamy", "clay_loam", "alluvial", "red"],
            "ph_range": [5.5, 7.0],
            "drainage": "moderate",
        },
        "climate_requirements": {
            "temp_range": [15, 38],
            "optimal_temp": 28,
            "humidity_range": [60, 90],
            "rainfall_mm": [1000, 2000],
        },
        "water_requirement": "high",
        "irrigation_compatibility": ["drip", "sprinkler", "flood"],
        "season_suitability": {"kharif": 0.8, "rabi": 0.7, "summer": 0.8},
        "growth_duration_days": [270, 365],
        "risk_factors": ["panama_wilt", "sigatoka"],
        "source": "ICAR-National Research Centre on Banana",
        "source_version": "v1.0",
    },
    "mango": {
        "crop_id": "mango",
        "name_en": "Mango",
        "name_te": "\u0c2e\u0c3e\u0c2e\u0c3f\u0c21\u0c3f",
        "category": "Fruits",
        "scientific_name": "Mangifera indica",
        "soil_requirements": {
            "soil_types": ["loamy", "sandy_loam", "red", "alluvial"],
            "ph_range": [5.5, 7.5],
            "drainage": "well_drained",
        },
        "climate_requirements": {
            "temp_range": [15, 40],
            "optimal_temp": 30,
            "humidity_range": [40, 70],
            "rainfall_mm": [750, 1500],
        },
        "water_requirement": "medium",
        "irrigation_compatibility": ["drip", "sprinkler"],
        "season_suitability": {"kharif": 0.6, "rabi": 0.5, "summer": 0.7},
        "growth_duration_days": None,
        "risk_factors": ["anthracnose", "powdery_mildew"],
        "source": "ICAR-Indian Institute of Horticultural Research",
        "source_version": "v1.0",
    },
    "papaya": {
        "crop_id": "papaya",
        "name_en": "Papaya",
        "name_te": "\u0c2c\u0c40\u0c21",
        "category": "Fruits",
        "scientific_name": "Carica papaya",
        "soil_requirements": {
            "soil_types": ["loamy", "sandy_loam", "alluvial"],
            "ph_range": [5.5, 7.0],
            "drainage": "well_drained",
        },
        "climate_requirements": {
            "temp_range": [18, 38],
            "optimal_temp": 30,
            "humidity_range": [50, 80],
            "rainfall_mm": [600, 1200],
        },
        "water_requirement": "medium",
        "irrigation_compatibility": ["drip", "sprinkler", "flood"],
        "season_suitability": {"kharif": 0.7, "rabi": 0.6, "summer": 0.8},
        "growth_duration_days": [180, 270],
        "risk_factors": ["papaya_ring_spot_virus", "anthracnose"],
        "source": "ICAR-IIHR Bangalore",
        "source_version": "v1.0",
    },
    "guava": {
        "crop_id": "guava",
        "name_en": "Guava",
        "name_te": "\u0c1c\u0c3e\u0c2a\u0c3e",
        "category": "Fruits",
        "scientific_name": "Psidium guajava",
        "soil_requirements": {
            "soil_types": ["loamy", "sandy_loam", "alluvial", "red"],
            "ph_range": [5.0, 7.5],
            "drainage": "moderate",
        },
        "climate_requirements": {
            "temp_range": [15, 38],
            "optimal_temp": 28,
            "humidity_range": [50, 80],
            "rainfall_mm": [500, 1200],
        },
        "water_requirement": "medium",
        "irrigation_compatibility": ["drip", "sprinkler", "flood"],
        "season_suitability": {"kharif": 0.7, "rabi": 0.6, "summer": 0.7},
        "growth_duration_days": None,
        "risk_factors": ["fruit_fly", "wilt"],
        "source": "ICAR-IIHR Bangalore",
        "source_version": "v1.0",
    },
    "pomegranate": {
        "crop_id": "pomegranate",
        "name_en": "Pomegranate",
        "name_te": "\u0c26\u0c3e\u0c28\u0c4d\u0d21\u0c2e\u0c28\u0c4d",
        "category": "Fruits",
        "scientific_name": "Punica granatum",
        "soil_requirements": {
            "soil_types": ["sandy_loam", "loamy", "red"],
            "ph_range": [6.0, 7.5],
            "drainage": "well_drained",
        },
        "climate_requirements": {
            "temp_range": [18, 38],
            "optimal_temp": 30,
            "humidity_range": [30, 60],
            "rainfall_mm": [400, 600],
        },
        "water_requirement": "medium",
        "irrigation_compatibility": ["drip", "sprinkler"],
        "season_suitability": {"kharif": 0.5, "rabi": 0.6, "summer": 0.7},
        "growth_duration_days": None,
        "risk_factors": ["bacterial_blight", "cercospora"],
        "source": "ICAR-IIHR Bangalore",
        "source_version": "v1.0",
    },

    # ===== SPICES =====
    "chilli": {
        "crop_id": "chilli",
        "name_en": "Chilli",
        "name_te": "\u0c2e\u0c3f\u0c30\u0c2a",
        "category": "Spices",
        "scientific_name": "Capsicum annuum",
        "soil_requirements": {
            "soil_types": ["loamy", "clay_loam", "sandy_loam"],
            "ph_range": [6.0, 7.5],
            "drainage": "well_drained",
        },
        "climate_requirements": {
            "temp_range": [20, 35],
            "optimal_temp": 28,
            "humidity_range": [50, 75],
            "rainfall_mm": [500, 800],
        },
        "water_requirement": "medium",
        "irrigation_compatibility": ["drip", "sprinkler", "flood"],
        "season_suitability": {"kharif": 0.7, "rabi": 0.85, "summer": 0.5},
        "growth_duration_days": [90, 120],
        "risk_factors": ["fruit_rot", "mosaic_virus", "thrips"],
        "source": "ICAR-National Research Centre on Seed Spices",
        "source_version": "v1.0",
    },
    "turmeric": {
        "crop_id": "turmeric",
        "name_en": "Turmeric",
        "name_te": "\u0c2a\u0c38\u0c41\u0c2a\u0c41",
        "category": "Spices",
        "scientific_name": "Curcuma longa",
        "soil_requirements": {
            "soil_types": ["loamy", "clay_loam", "red", "alluvial"],
            "ph_range": [5.0, 7.5],
            "drainage": "moderate",
        },
        "climate_requirements": {
            "temp_range": [20, 38],
            "optimal_temp": 30,
            "humidity_range": [60, 90],
            "rainfall_mm": [1000, 2000],
        },
        "water_requirement": "high",
        "irrigation_compatibility": ["drip", "sprinkler", "flood"],
        "season_suitability": {"kharif": 0.9, "rabi": 0.3, "summer": 0.1},
        "growth_duration_days": [210, 270],
        "risk_factors": ["rhizome_rot", "leaf_blotch"],
        "source": "ICAR-National Bureau of Plant Genetic Resources",
        "source_version": "v1.0",
    },
    "ginger": {
        "crop_id": "ginger",
        "name_en": "Ginger",
        "name_te": "\u0c05\u0c32\u0c4d\u0c32\u0c02",
        "category": "Spices",
        "scientific_name": "Zingiber officinale",
        "soil_requirements": {
            "soil_types": ["loamy", "clay_loam", "red", "alluvial"],
            "ph_range": [5.5, 7.0],
            "drainage": "well_drained",
        },
        "climate_requirements": {
            "temp_range": [20, 35],
            "optimal_temp": 28,
            "humidity_range": [60, 90],
            "rainfall_mm": [1000, 2000],
        },
        "water_requirement": "high",
        "irrigation_compatibility": ["drip", "sprinkler"],
        "season_suitability": {"kharif": 0.9, "rabi": 0.2, "summer": 0.1},
        "growth_duration_days": [210, 270],
        "risk_factors": ["rhizome_rot", "soft_rot"],
        "source": "ICAR-National Bureau of Plant Genetic Resources",
        "source_version": "v1.0",
    },

    # ===== FIBRE CROPS =====
    "cotton": {
        "crop_id": "cotton",
        "name_en": "Cotton",
        "name_te": "\u0c2a\u0c24\u0c4d\u0d24\u0c3f",
        "category": "Fibre",
        "scientific_name": "Gossypium spp.",
        "soil_requirements": {
            "soil_types": ["black", "clay_loam", "loamy"],
            "ph_range": [6.0, 8.0],
            "drainage": "moderate",
        },
        "climate_requirements": {
            "temp_range": [20, 38],
            "optimal_temp": 30,
            "humidity_range": [40, 80],
            "rainfall_mm": [600, 1200],
        },
        "water_requirement": "medium",
        "irrigation_compatibility": ["drip", "sprinkler", "flood"],
        "season_suitability": {"kharif": 0.95, "rabi": 0.2, "summer": 0.1},
        "growth_duration_days": [150, 180],
        "risk_factors": ["bollworm", "bacterial_blight", "fusarium_wilt"],
        "source": "ICAR-Central Institute for Cotton Research",
        "source_version": "v1.0",
    },
    "jute": {
        "crop_id": "jute",
        "name_en": "Jute",
        "name_te": "\u0c1c\u0c1f",
        "category": "Fibre",
        "scientific_name": "Corchorus spp.",
        "soil_requirements": {
            "soil_types": ["clay", "loamy", "alluvial"],
            "ph_range": [5.5, 7.5],
            "drainage": "poor_to_moderate",
        },
        "climate_requirements": {
            "temp_range": [20, 38],
            "optimal_temp": 30,
            "humidity_range": [60, 90],
            "rainfall_mm": [1000, 2000],
        },
        "water_requirement": "high",
        "irrigation_compatibility": ["flood", "sprinkler"],
        "season_suitability": {"kharif": 0.95, "rabi": 0.1, "summer": 0.05},
        "growth_duration_days": [120, 150],
        "risk_factors": ["stem_rot", "anthracnose"],
        "source": "ICAR-Central Research Institute for Jute and Allied Fibres",
        "source_version": "v1.0",
    },

    # ===== SUGAR/STARCH =====
    "sugarcane": {
        "crop_id": "sugarcane",
        "name_en": "Sugarcane",
        "name_te": "\u0c1a\u0c46\u0c30\u0c4d\u0d15",
        "category": "Sugar/Starch",
        "scientific_name": "Saccharum officinarum",
        "soil_requirements": {
            "soil_types": ["loamy", "clay_loam", "alluvial", "black"],
            "ph_range": [6.0, 7.5],
            "drainage": "moderate",
        },
        "climate_requirements": {
            "temp_range": [20, 40],
            "optimal_temp": 30,
            "humidity_range": [60, 90],
            "rainfall_mm": [1000, 2000],
        },
        "water_requirement": "very_high",
        "irrigation_compatibility": ["flood", "drip", "sprinkler"],
        "season_suitability": {"kharif": 0.85, "rabi": 0.7, "summer": 0.5},
        "growth_duration_days": [300, 400],
        "risk_factors": ["red_rot", "smut", "drought"],
        "source": "ICAR-Sugarcane Research Institute",
        "source_version": "v1.0",
    },
    "sweet_potato": {
        "crop_id": "sweet_potato",
        "name_en": "Sweet Potato",
        "name_te": "\u0c24\u0c40\u0c28\u0c3e\u0c32\u0c41",
        "category": "Sugar/Starch",
        "scientific_name": "Ipomoea batatas",
        "soil_requirements": {
            "soil_types": ["sandy_loam", "loamy", "alluvial"],
            "ph_range": [5.5, 6.5],
            "drainage": "well_drained",
        },
        "climate_requirements": {
            "temp_range": [20, 35],
            "optimal_temp": 28,
            "humidity_range": [50, 80],
            "rainfall_mm": [500, 1000],
        },
        "water_requirement": "medium",
        "irrigation_compatibility": ["drip", "rainfed", "flood"],
        "season_suitability": {"kharif": 0.8, "rabi": 0.6, "summer": 0.5},
        "growth_duration_days": [90, 120],
        "risk_factors": ["root_rot", "sweet_potato_weevil"],
        "source": "ICAR-Central Tuber Crops Research Institute",
        "source_version": "v1.0",
    },

    # ===== COFFEE =====
    "coffee": {
        "crop_id": "coffee",
        "name_en": "Coffee",
        "name_te": "\u0c15\u0c3e\u0c2b\u0c40",
        "category": "Commercial",
        "scientific_name": "Coffea arabica / canephora",
        "soil_requirements": {
            "soil_types": ["loamy", "red", "clay_loam"],
            "ph_range": [5.0, 6.5],
            "drainage": "well_drained",
        },
        "climate_requirements": {
            "temp_range": [15, 28],
            "optimal_temp": 22,
            "humidity_range": [50, 80],
            "rainfall_mm": [1000, 2000],
        },
        "water_requirement": "medium",
        "irrigation_compatibility": ["rainfed", "drip"],
        "season_suitability": {"kharif": 0.6, "rabi": 0.6, "summer": 0.6},
        "growth_duration_days": None,
        "risk_factors": ["coffee_leaf_rust", "coffee_berry_disease"],
        "source": "ICAR-Coffee Board",
        "source_version": "v1.0",
    },
}


# =============================================================================
# CATEGORIES
# =============================================================================

CATALOG_CATEGORIES = {
    "Cereals": ["rice", "maize", "wheat", "sorghum"],
    "Millets": ["pearl_millet", "finger_millet"],
    "Pulses": ["chickpea", "pigeon_pea", "green_gram", "black_gram", "lentil"],
    "Oilseeds": ["groundnut", "soybean", "sunflower", "sesame", "mustard"],
    "Vegetables": ["tomato", "onion", "potato", "okra", "brinjal", "cabbage"],
    "Fruits": ["banana", "mango", "papaya", "guava", "pomegranate"],
    "Spices": ["chilli", "turmeric", "ginger"],
    "Fibre": ["cotton", "jute"],
    "Sugar/Starch": ["sugarcane", "sweet_potato"],
    "Commercial": ["coffee"],
}


# =============================================================================
# ALIASES (for canonical ID mapping)
# =============================================================================

CROP_ALIASES: Dict[str, str] = {
    "tomatoes": "tomato",
    "tomato": "tomato",
    "rice": "rice",
    "paddy": "rice",
    "wheat": "wheat",
    "maize": "maize",
    "corn": "maize",
    "cotton": "cotton",
    "chilli": "chilli",
    "chili": "chilli",
    "chillies": "chilli",
    "onion": "onion",
    "onions": "onion",
    "potato": "potato",
    "potatoes": "potato",
    "brinjal": "brinjal",
    "eggplant": "brinjal",
    "okra": "okra",
    "ladies finger": "okra",
    "cabbage": "cabbage",
    "banana": "banana",
    "mango": "mango",
    "mangoes": "mango",
    "papaya": "papaya",
    "guava": "guava",
    "pomegranate": "pomegranate",
    "groundnut": "groundnut",
    "peanut": "groundnut",
    "peanuts": "groundnut",
    "soybean": "soybean",
    "soya": "soybean",
    "sunflower": "sunflower",
    "sesame": "sesame",
    "til": "sesame",
    "mustard": "mustard",
    "chickpea": "chickpea",
    "chana": "chickpea",
    "bengal gram": "chickpea",
    "pigeon pea": "pigeon_pea",
    "arhar": "pigeon_pea",
    "tur dal": "pigeon_pea",
    "green gram": "green_gram",
    "moong": "green_gram",
    "black gram": "black_gram",
    "urad": "black_gram",
    "lentil": "lentil",
    "masoor": "lentil",
    "sugarcane": "sugarcane",
    "sweet potato": "sweet_potato",
    "sweet potatoes": "sweet_potato",
    "coffee": "coffee",
    "turmeric": "turmeric",
    "haldi": "turmeric",
    "ginger": "ginger",
    "allam": "ginger",
    "jute": "jute",
    "sorghum": "sorghum",
    "jowar": "sorghum",
    "pearl millet": "pearl_millet",
    "bajra": "pearl_millet",
    "finger millet": "finger_millet",
    "ragi": "finger_millet",
    "cotton": "cotton",
}


def get_canonical_id(name: str) -> Optional[str]:
    """Resolve any crop name/alias to canonical crop_id."""
    lower = name.lower().strip()
    if lower in CROP_ALIASES:
        return CROP_ALIASES[lower]
    if lower in CROP_CATALOG:
        return lower
    return None


def get_crop(crop_id: str) -> Optional[Dict[str, Any]]:
    """Get crop by canonical ID."""
    return CROP_CATALOG.get(crop_id)


def get_all_crop_ids() -> List[str]:
    """Return all canonical crop IDs."""
    return list(CROP_CATALOG.keys())


def get_crops_by_category(category: str) -> List[Dict[str, Any]]:
    """Return all crops in a category."""
    crop_ids = CATALOG_CATEGORIES.get(category, [])
    return [CROP_CATALOG[cid] for cid in crop_ids if cid in CROP_CATALOG]
