import { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { useAuth } from './AuthContext';

type Language = 'en' | 'te';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    dashboard: 'Dashboard',
    cropRecommendation: 'Crop AI',
    disease: 'Disease',
    weather: 'Weather',
    decisions: 'Decisions',
    scenarios: 'Scenarios',
    expenses: 'Expenses',
    harvest: 'Harvest',
    insights: 'Insights',
    aiIntelligence: 'AI Intelligence',
    assistant: 'Assistant',
    profile: 'Profile',
    logout: 'Logout',
    welcome: 'Welcome',
    goodMorning: 'Good morning',
    goodAfternoon: 'Good afternoon',
    goodEvening: 'Good evening',
    currentFarm: 'Current Farm',
    currentField: 'Current Field',
    currentCrop: 'Current Crop',
    todayDecision: "Today's Decision",
    recommendedAction: 'Recommended Action',
    why: 'Why?',
    compareWhatIf: 'Compare What-If',
    weatherSummary: 'Weather Summary',
    diseaseSummary: 'Disease Summary',
    cropHealth: 'Crop Health',
    totalCost: 'Total Cost',
    netProfit: 'Net Profit',
    revenue: 'Revenue',
    uploadLeaf: 'Upload a clear crop leaf image',
    loadingModel: 'Loading crop vision model...',
    analyzing: 'Analyzing leaf...',
    diseaseDetected: 'Disease detected',
    confidence: 'Confidence',
    severity: 'Severity',
    high: 'High',
    medium: 'Medium',
    low: 'Low',
    shouldIrrigate: 'Should I irrigate today?',
    whyRisky: 'Why is my crop at risk?',
    whatNext: 'What should I do next?',
    explainRecommendation: "Explain today's recommendation",
    analyzingContext: 'Analyzing your farm context...',
    enterSoilValues: 'Enter soil and environmental values',
    temperature: 'Temperature',
    humidity: 'Humidity',
    rainfall: 'Rainfall',
    soilPH: 'Soil pH',
    nitrogen: 'Nitrogen (N)',
    phosphorus: 'Phosphorus (P)',
    potassium: 'Potassium (K)',
    getRecommendation: 'Get Recommendation',
    recommendedCrop: 'Recommended Crop',
    suitability: 'Suitability',
    topAlternatives: 'Top Alternatives',
    whyThisRecommendation: 'Why this recommendation?',
    modelExplanation: 'The model ranked this crop highest for the supplied soil and environmental conditions.',
    delayedIrrigation: 'Delay irrigation by 1 day',
    rainExpected: 'Rain is expected soon.',
    soilMoisture: 'Current soil/water state does not indicate urgent irrigation.',
    fungalRisk: 'Disease/fungal conditions make excess moisture undesirable.',
    category: 'Category',
    amount: 'Amount',
    date: 'Date',
    description: 'Description',
    seeds: 'Seeds',
    fertilizer: 'Fertilizer',
    pesticides: 'Pesticides',
    labour: 'Labour',
    irrigation: 'Irrigation',
    transport: 'Transport',
    equipment: 'Equipment',
    other: 'Other',
    addExpense: 'Add Expense',
    noExpenses: 'No cultivation expenses recorded yet.',
    harvestDate: 'Harvest Date',
    quantity: 'Quantity',
    unit: 'Unit',
    sellingPrice: 'Selling Price',
    buyer: 'Buyer',
    market: 'Market',
    recordHarvest: 'Record Harvest',
    noHarvest: 'Record your first harvest to see profitability.',
    predicted: 'Predicted',
    actual: 'Actual',
    difference: 'Difference',
    deviation: 'Deviation',
    predictionDeviation: 'Prediction deviation',
    currentPlan: 'Current plan',
    delayIrrigation: 'Delay irrigation',
    increaseIrrigation: 'Increase irrigation',
    bestOption: 'Best option',
    createScenario: 'Create Scenario',
    scenarioName: 'Scenario Name',
    create: 'Create',
    english: 'English',
    telugu: 'తెలుగు',
    liveWeather: 'LIVE WEATHER',
    modelPrediction: 'MODEL PREDICTION',
    estimatedValues: 'ESTIMATED VALUES',
    cachedWeather: 'CACHED WEATHER',
    simulatedData: 'SIMULATED DATA',
    disclaimer: 'AI classification is an assistive prediction and should be verified with an agricultural expert when necessary.',
    source: 'Source',
    modelVersion: 'Model',
    updated: 'Updated',
    home: 'Home',
    crops: 'Crops',
    health: 'Health',
    more: 'More',
    selectLocation: 'Select Your Location',
    state: 'State',
    district: 'District',
    mandal: 'Mandal',
    town: 'Town',
    selectState: 'Select State',
    selectDistrict: 'Select District',
    selectMandal: 'Select Mandal',
    selectTown: 'Select Town',
    selectStateFirst: 'Select state first',
    selectDistrictFirst: 'Select district first',
    selectMandalFirst: 'Select mandal first',
    additionalInfo: 'Additional Information',
    season: 'Season',
    kharif: 'Kharif',
    rabi: 'Rabi',
    zaid: 'Zaid',
    soilType: 'Soil Type',
    gettingRecommendation: 'Getting AI recommendation...',
    getCropRecommendation: 'Get Crop Recommendation',
    startThisCrop: 'Start This Crop',
    whyRecommended: 'Why this crop is recommended',
    favorableFactors: 'Favorable Factors',
    limitingFactors: 'Limiting Factors',
    waterRequirement: 'Water requirement',
    risks: 'Risks',
    locationAdvice: 'Location-specific advice',
    alternativeCrops: 'Alternative Crops',
    select: 'Select',
    startCrop: 'Start Crop',
    cropStarted: 'Crop Started!',
    cropStartedMessage: 'has been added to your farm',
    goToDashboard: 'Go to Dashboard',
    analyzeDisease: 'Analyze Disease',
    uploadLeafImage: 'Upload Leaf Image',
    supportedCrops: 'Supported Crops',
    viewAll: 'View All',
    allCrops: 'All Crops',
    cropHealthTimeline: 'Crop Health Timeline',
    previousAssessment: 'Previous Assessment',
    currentAssessment: 'Current Assessment',
    healthTrend: 'Health Trend',
    improving: 'Improving',
    declining: 'Declining',
    stable: 'Stable',
    followUpRequired: 'Follow-up Required',
    nextCheckDate: 'Next Check Date',
    viewHistory: 'View History',
    aboutHarvex: 'About HARVEX',
    ourMission: 'Our Mission',
    ourVision: 'Our Vision',
    keyFeatures: 'Key Features',
    contactUs: 'Contact Us',
    version: 'Version',
    loadingExpenses: 'Loading expenses...',
    loadingHarvests: 'Loading harvest records...',
    loadingWeather: 'Loading weather...',
    fetchingWeather: 'Fetching weather data for your farm',
    tryAgain: 'Try Again',
    noActiveCrop: 'No active crop',
    startCropToTrack: 'Start a crop to track expenses',
    startCropToRecord: 'Start a crop to record harvests',
    noExpensesRecorded: 'No expenses recorded yet',
    startTrackingCosts: 'Start tracking your cultivation costs',
    addFirstExpense: 'Add First Expense',
    saveExpense: 'Save Expense',
    noHarvestRecorded: 'No harvest recorded yet',
    recordFirstHarvest: 'Record First Harvest',
    saveHarvest: 'Save Harvest',
    totalExpenses: 'Total Expenses',
    totalHarvest: 'Total Harvest',
    trackCosts: 'Track all your cultivation costs',
    trackHarvest: 'Track your harvest and revenue',
    setFarmLocation: 'Set your farm location',
    setLocationDesc: 'Set your farm location to get weather information',
    weatherUnavailable: 'Weather temporarily unavailable',
    weatherUnavailableDesc: 'Unable to fetch weather data. Please try again.',
    farmWeather: 'Weather data for your farm',
    refreshWeather: 'Refresh Weather',
    cancel: 'Cancel',
    diseaseDetection: 'Disease Detection',
    uploadImage: 'Upload Leaf Image',
    analyzeImage: 'Analyzing Image',
    crop: 'Crop',
    healthy: 'Healthy',
    unableToDetermine: 'Unable to Determine',
    visualEvidence: 'Visual Evidence',
    explanation: 'Explanation',
    treatment: 'Treatment',
    precautions: 'Precautions',
    followUp: 'Follow-up',
    risk: 'Risk',
    smartCropRecommendation: 'Smart Crop Recommendation',
    harvexAnalysis: 'HARVEX analyzes your farm conditions and recommends suitable crops for your land.',
    farmLocation: 'Farm Location',
    useGps: 'Use My GPS Location',
    orEnterManually: 'or enter manually',
    latitude: 'Latitude',
    longitude: 'Longitude',
    farmConditions: 'Farm Conditions',
    waterAvailability: 'Water Availability',
    veryLimited: 'Very Limited',
    limited: 'Limited',
    moderate: 'Moderate',
    good: 'Good',
    abundant: 'Abundant',
    rainfedOnly: 'Rainfed Only',
    irrigationMethod: 'Irrigation Method',
    drip: 'Drip',
    sprinkler: 'Sprinkler',
    flood: 'Flood',
    furrow: 'Furrow',
    rainfed: 'Rainfed',
    otherMethod: 'Other',
    getCropRecButton: 'Get Crop Recommendations',
    analyzingFarm: 'HARVEX is analyzing your farm',
    locationReceived: 'Location received',
    conditionsLoaded: 'Farm conditions loaded',
    weatherChecked: 'Weather checked',
    soilChecked: 'Soil information checked',
    aiResearching: 'AI is researching suitable crops',
    rankingCrops: 'Ranking suitable crops',
    analysisComplete: 'Analysis complete',
    pleaseWait: 'Please wait while HARVEX compares your farm conditions with suitable crops.',
    examiningCrop: 'HARVEX is examining your crop',
    imageUploaded: 'Image uploaded',
    qualityChecked: 'Image quality checked',
    aiExamining: 'AI is examining visible symptoms',
    identifyingCondition: 'Identifying possible crop condition',
    preparingExplanation: 'Preparing explanation',
    suitabilityScore: 'Suitability Score',
    whyRecommendedShort: 'Why recommended',
    soilCompatibility: 'Soil compatibility',
    climateCompatibility: 'Climate compatibility',
    waterCompatibility: 'Water compatibility',
    seasonSuitability: 'Season suitability',
    locationSuitability: 'Location suitability',
    irrigationCompatibility: 'Irrigation compatibility',
    dataSource: 'Data source',
    estimated: 'Estimated',
    measured: 'Measured',
    farmerProvided: 'Farmer provided',
    unavailable: 'Unavailable',
    viewDetails: 'View Details',
    collapseDetails: 'Collapse Details',
    aiVisualAssessment: 'AI Visual Assessment',
    healthGuidance: 'Health Guidance',
    treatmentGuidance: 'Treatment Guidance',
    immediateActions: 'Immediate Actions',
    culturalPractices: 'Cultural / Organic Practices',
    chemicalControl: 'Chemical Control',
    safetyNote: 'Safety Note',
    followUpIn: 'Follow-up recommended in',
    routineCheck: 'Next routine check in',
    days: 'days',
    imageQualityGuidance: 'Image Quality Guidance',
    nextSteps: 'Next Steps',
    tryAgainIn: 'Try again in',
    clearerImage: 'with a clearer image',
    followUpRecommended: 'Follow-up Recommended',
    uploadAnother: 'Upload another image in a few days to reassess the plant condition.',
    aiUnavailableTitle: 'AI Analysis Temporarily Unavailable',
    nvidiaUnavailableDesc: 'NVIDIA Vision AI is temporarily unavailable. Please try again later. Your uploaded image has not been converted into a diagnosis.',
    detectionNotAvailable: 'Detection Not Available',
    tipClearPhoto: 'Tip: Use a clear, well-lit close-up photo of the affected leaf area.',
    noDiseaseFound: 'No disease detected',
    provider: 'Provider',
    model: 'Model',
    severeSeverity: 'Severe',
    moderateSeverity: 'Moderate',
    mildSeverity: 'Mild',
    noneSeverity: 'None',
    funLoadingNote1: 'Checking if your soil has more ambition than your neighbors...',
    funLoadingNote2: 'Asking the cows for their opinion on crop rotation...',
    funLoadingNote3: 'Calculating how many sunflowers to plant for maximum happiness...',
    funLoadingNote4: 'Cross-referencing with ancient farming almanacs...',
    funLoadingNote5: 'Even your crop takes longer to grow! Patience, farmer...',
    funLoadingNote6: 'The AI is asking the moon for planting advice...',
    funLoadingNote7: 'Checking if the rooster agrees with this recommendation...',
    funLoadingNote8: 'Optimizing for maximum tastiness of your future harvest...',
    funDiseaseNote1: 'Looking at your leaf very carefully...',
    funDiseaseNote2: 'Asking the plant doctor for a second opinion...',
    funDiseaseNote3: 'The AI is squinting really hard at your leaf...',
    funDiseaseNote4: 'Even doctors need time to read X-rays! Relax...',
    funDiseaseNote5: 'Comparing your leaf with 10,000 healthy leaves...',
    loadingInsights: 'Loading farm insights...',
    generatingInsights: 'Generating insights...',
    noInsightsData: 'Not enough farm data yet',
    noInsightsDataDesc: 'Add expenses, harvests, or crop information to get AI-powered insights.',
    insightsUnavailable: 'Farm insights are temporarily unavailable.',
    insightsUnavailableDesc: 'The AI service could not generate insights right now.',
    noActiveCropInsights: 'No active crop',
    noActiveCropInsightsDesc: 'Start a crop to get AI-powered farm insights.',
    aiSummary: 'AI Summary',
    refreshInsights: 'Refresh Insights',
    resultAvailable: 'Result available',
    viewResult: 'View Result',
    resultUnavailable: 'Unable to load this recommendation.',
    cropRecommendationResult: 'Crop Recommendation',
    riskAnalysisResult: 'Risk Analysis',
    irrigationAdviceResult: 'Irrigation Advice',
    financialAnalysisResult: 'Financial Analysis',
    farmInsightsResult: 'Farm Insights',
    majorRisks: 'Major Risks',
    overallRisk: 'Overall Risk',
    keyConcerns: 'Key Concerns',
    urgentActions: 'Urgent Actions',
    irrigationRecommendation: 'Recommendation',
    farmSummary: 'Farm Summary',
    totalExpensesLabel: 'Total Expenses',
    totalRevenueLabel: 'Total Revenue',
    harvestCount: 'Harvest Count',
    insightCategory: 'Category',
    insightPriority: 'Priority',
    insightSource: 'Source',
    close: 'Close',
  },
  te: {
    dashboard: 'డాష్‌బోర్డ్',
    cropRecommendation: 'పంట AI',
    disease: 'వ్యాధి',
    weather: 'వాతావరణం',
    decisions: 'నిర్ణయాలు',
    scenarios: 'సినారియోలు',
    expenses: 'ఖర్చులు',
    harvest: 'కోత',
    insights: 'అంతర్దృష్టులు',
    aiIntelligence: 'AI ఇంటెలిజెన్స్',
    assistant: 'సహాయకుడు',
    profile: 'ప్రొఫైల్',
    logout: 'లాగ్అవుట్',
    welcome: 'స్వాగతం',
    goodMorning: 'శుభోదయం',
    goodAfternoon: 'శుభ మధ్యాహ్నం',
    goodEvening: 'శుభ సాయంత్రం',
    currentFarm: 'ప్రస్తుత పొలం',
    currentField: 'ప్రస్తుత పొలం',
    currentCrop: 'ప్రస్తుత పంట',
    todayDecision: 'ఈ రోజు నిర్ణయం',
    recommendedAction: 'సిఫార్సు చేయబడిన చర్య',
    why: 'ఎందుకు?',
    compareWhatIf: 'ఏమి జరిగితే పోల్చండి',
    weatherSummary: 'వాతావరణ సారాంశం',
    diseaseSummary: 'వ్యాధి సారాంశం',
    cropHealth: 'పంట ఆరోగ్యం',
    totalCost: 'మొత్తం ఖర్చు',
    netProfit: 'నికర లాభం',
    revenue: 'ఆదాయం',
    uploadLeaf: 'స్పష్టమైన పంట ఆకు చిత్రాన్ని అప్‌లోడ్ చేయండి',
    loadingModel: 'పంట దృష్టి మోడల్ లోడ్ అవుతోంది...',
    analyzing: 'ఆకును విశ్లేషిస్తోంది...',
    diseaseDetected: 'వ్యాధి గుర్తించబడింది',
    confidence: 'నమ్మకం',
    severity: 'తీవ్రత',
    high: 'ఎక్కువ',
    medium: 'మధ్యస్థం',
    low: 'తక్కువ',
    shouldIrrigate: 'నేను ఈ రోజు నీటిపారుదల చేయాలా?',
    whyRisky: 'నా పంట ప్రమాదంలో ఉందా?',
    whatNext: 'నేను తదుపరి ఏమి చేయాలి?',
    explainRecommendation: 'ఈ రోజు సిఫార్సును వివరించండి',
    analyzingContext: 'మీ పొలం సందర్భాన్ని విశ్లేషిస్తోంది...',
    enterSoilValues: 'నేల మరియు పర్యావరణ విలువలను నమోదు చేయండి',
    temperature: 'ఉష్ణోగ్రత',
    humidity: 'తేమ',
    rainfall: 'వర్షపాతం',
    soilPH: 'నేల pH',
    nitrogen: 'నత్రజని (N)',
    phosphorus: 'భాస్వరం (P)',
    potassium: 'పొటాషియం (K)',
    getRecommendation: 'సిఫార్సు పొందండి',
    recommendedCrop: 'సిఫార్సు చేయబడిన పంట',
    suitability: 'అనుకూలత',
    topAlternatives: 'టాప్ ప్రత్యామ్నాయాలు',
    whyThisRecommendation: 'ఈ సిఫార్సు ఎందుకు?',
    modelExplanation: 'మోడల్ సరఫరా చేయబడిన నేల మరియు పర్యావరణ పరిస్థితుల కోసం ఈ పంటను అత్యధికంగా ర్యాంక్ చేసింది.',
    delayedIrrigation: 'నీటిపారుదలను 1 రోజు ఆలస్యం చేయండి',
    rainExpected: 'త్వరలో వర్షం అనిపిస్తోంది.',
    soilMoisture: 'ప్రస్తుత నేల/నీటి స్థితి అత్యవసర నీటిపారుదలను సూచించడం లేదు.',
    fungalRisk: 'వ్యాధి/శిలీంధ్ర పరిస్థితులు అధిక తేమను అవాంఛనీయం చేస్తాయి.',
    category: 'వర్గం',
    amount: 'మొత్తం',
    date: 'తేదీ',
    description: 'వివరణ',
    seeds: 'విత్తనాలు',
    fertilizer: 'ఎరువులు',
    pesticides: 'పురుగుమందులు',
    labour: 'శ్రమ',
    irrigation: 'నీటిపారుదల',
    transport: 'రవాణా',
    equipment: 'పరికరాలు',
    other: 'ఇతర',
    addExpense: 'ఖర్చు జోడించండి',
    noExpenses: 'ప్రస్తుతం సాగు ఖర్చులు నమోదు చేయబడలేదు.',
    harvestDate: 'కోత తేదీ',
    quantity: 'పరిమాణం',
    unit: 'యూనిట్',
    sellingPrice: 'అమ్మకపు ధర',
    buyer: 'కొనుగోలుదారు',
    market: 'మార్కెట్',
    recordHarvest: 'కోత నమోదు చేయండి',
    noHarvest: 'లాభదాయకతను చూడటానికి మీ మొదటి కోతను నమోదు చేయండి.',
    predicted: 'అంచనా',
    actual: 'వాస్తవ',
    difference: 'తేడా',
    deviation: 'విచలనం',
    predictionDeviation: 'అంచనా విచలనం',
    currentPlan: 'ప్రస్తుత ప్రణాళిక',
    delayIrrigation: 'నీటిపారుదల ఆలస్యం',
    increaseIrrigation: 'నీటిపారుదల పెంచండి',
    bestOption: 'ఉత్తమ ఎంపిక',
    createScenario: 'సినారియో సృష్టించండి',
    scenarioName: 'సినారియో పేరు',
    create: 'సృష్టించండి',
    english: 'English',
    telugu: 'తెలుగు',
    liveWeather: 'LIVE WEATHER',
    modelPrediction: 'MODEL PREDICTION',
    estimatedValues: 'ESTIMATED VALUES',
    cachedWeather: 'CACHED WEATHER',
    simulatedData: 'SIMULATED DATA',
    disclaimer: 'AI వర్గీకరణ ఒక సహాయక అంచనా మరియు అవసరమైనప్పుడు వ్యవసాయ నిపుణుడితో ధృవీకరించబడాలి.',
    source: 'మూలం',
    modelVersion: 'మోడల్',
    updated: 'నవీకరించబడింది',
    home: 'హోమ్',
    crops: 'పంటలు',
    health: 'ఆరోగ్యం',
    more: 'మరిన్ని',
    selectLocation: 'మీ స్థానాన్ని ఎంచుకోండి',
    state: 'రాష్ట్రం',
    district: 'జిల్లా',
    mandal: 'మండలం',
    town: 'పట్టణం',
    selectState: 'రాష్ట్రాన్ని ఎంచుకోండి',
    selectDistrict: 'జిల్లాను ఎంచుకోండి',
    selectMandal: 'మండలాన్ని ఎంచుకోండి',
    selectTown: 'పట్టణాన్ని ఎంచుకోండి',
    selectStateFirst: 'మొదలుగా రాష్ట్రాన్ని ఎంచుకోండి',
    selectDistrictFirst: 'మొదలుగా జిల్లాను ఎంచుకోండి',
    selectMandalFirst: 'మొదలుగా మండలాన్ని ఎంచుకోండి',
    additionalInfo: 'అదనపు సమాచారం',
    season: 'సీజన్',
    kharif: 'ఖరీఫ్',
    rabi: 'రబీ',
    zaid: 'జాయ్ద్',
    soilType: 'నేల రకం',
    gettingRecommendation: 'AI సిఫార్సు పొందుతోంది...',
    getCropRecommendation: 'పంట సిఫార్సు పొందండి',
    startThisCrop: 'ఈ పంటను ప్రారంభించండి',
    whyRecommended: 'ఈ పంట ఎందుకు సిఫార్సు చేయబడింది',
    favorableFactors: 'అనుకూల కారకాలు',
    limitingFactors: 'పరిమిత కారకాలు',
    waterRequirement: 'నీటి అవసరం',
    risks: 'ప్రమాదాలు',
    locationAdvice: 'స్థాన-నిర్దిష్ట సలహా',
    alternativeCrops: 'ప్రత్యామ్నాయ పంటలు',
    select: 'ఎంచుకోండి',
    startCrop: 'పంట ప్రారంభించండి',
    cropStarted: 'పంట ప్రారంభించబడింది!',
    cropStartedMessage: 'మీ పొలంలో జోడించబడింది',
    goToDashboard: 'డాష్‌బోర్డ్‌కు వెళ్ళండి',
    analyzeDisease: 'వ్యాధిని విశ్లేషించండి',
    uploadLeafImage: 'ఆకు చిత్రాన్ని అప్‌లోడ్ చేయండి',
    supportedCrops: 'మద్దతు ఉన్న పంటలు',
    viewAll: 'అన్నీ చూడండి',
    allCrops: 'అన్ని పంటలు',
    cropHealthTimeline: 'పంట ఆరోగ్య కాలక్రమం',
    previousAssessment: 'మునుపటి అంచనా',
    currentAssessment: 'ప్రస్తుత అంచనా',
    healthTrend: 'ఆరోగ్య ధోరణి',
    improving: 'మెరుగుపడుతోంది',
    declining: 'తగ్గుతోంది',
    stable: 'స్థిరం',
    followUpRequired: 'ఫాలో-అప్ అవసరం',
    nextCheckDate: 'తదుపరి తనిఖీ తేదీ',
    viewHistory: 'చరిత్ర చూడండి',
    aboutHarvex: 'HARVEX గురించి',
    ourMission: 'మా లక్ష్యం',
    ourVision: 'మా దృష్టి',
    keyFeatures: 'ముఖ్య లక్షణాలు',
    contactUs: 'మమ్మల్ని సంప్రదించండి',
    version: 'వెర్షన్',
    loadingExpenses: 'ఖర్చులు లోడ్ అవుతున్నాయి...',
    loadingHarvests: 'కోత రికార్డులు లోడ్ అవుతున్నాయి...',
    loadingWeather: 'వాతావరణం లోడ్ అవుతోంది...',
    fetchingWeather: 'మీ పొలం కోసం వాతావరణ డేటా పొందుతోంది',
    tryAgain: 'మళ్ళీ ప్రయత్నించండి',
    noActiveCrop: 'ప్రస్తుతం పంట లేదు',
    startCropToTrack: 'ఖర్చులను ట్రాక్ చేయడానికి పంటను ప్రారంభించండి',
    startCropToRecord: 'కోతలను నమోదు చేయడానికి పంటను ప్రారంభించండి',
    noExpensesRecorded: 'ఇంకా ఖర్చులు నమోదు చేయబడలేదు',
    startTrackingCosts: 'మీ సాగు ఖర్చులను ట్రాక్ చేయడం ప్రారంభించండి',
    addFirstExpense: 'మొదటి ఖర్చు జోడించండి',
    saveExpense: 'ఖర్చు సేవ్ చేయండి',
    noHarvestRecorded: 'ఇంకా కోత నమోదు చేయబడలేదు',
    recordFirstHarvest: 'మొదటి కోత నమోదు చేయండి',
    saveHarvest: 'కోత సేవ్ చేయండి',
    totalExpenses: 'మొత్తం ఖర్చులు',
    totalHarvest: 'మొత్తం కోత',
    trackCosts: 'మీ సాగు ఖర్చులన్నింటినీ ట్రాక్ చేయండి',
    trackHarvest: 'మీ కోత మరియు ఆదాయాన్ని ట్రాక్ చేయండి',
    setFarmLocation: 'మీ పొలం స్థానాన్ని సెట్ చేయండి',
    setLocationDesc: 'వాతావరణ సమాచారం పొందడానికి మీ పొలం స్థానాన్ని సెట్ చేయండి',
    weatherUnavailable: 'వాతావరణం తాత్కాలికంగా అందుబాటులో లేదు',
    weatherUnavailableDesc: 'వాతావరణ డేటాను పొందడం సాధ్యం కాలేదు. దయచేసి మళ్ళీ ప్రయత్నించండి.',
    farmWeather: 'మీ పొలం కోసం వాతావరణ సమాచారం',
    refreshWeather: 'వాతావరణం రిఫ్రెష్ చేయండి',
    cancel: 'రద్దు',
    diseaseDetection: 'వ్యాధి గుర్తింపు',
    uploadImage: 'ఆకు చిత్రాన్ని అప్‌లోడ్ చేయండి',
    analyzeImage: 'చిత్రాన్ని విశ్లేషిస్తోంది',
    crop: 'పంట',
    healthy: 'ఆరోగ్యంగా',
    unableToDetermine: 'నిర్ణయించడం సాధ్యం కాలేదు',
    visualEvidence: 'దృశ్య ఆధారాలు',
    explanation: 'వివరణ',
    treatment: 'చికిత్స',
    precautions: 'జాగ్రత్తలు',
    followUp: 'ఫాలో-అప్',
    risk: 'ప్రమాదం',
    smartCropRecommendation: 'స్మార్ట్ పంట సిఫార్సు',
    harvexAnalysis: 'మీ పొల పరిస్థితులను విశ్లేషించి మీ భూమికి అనుకూలమైన పంటలను HARVEX సిఫార్సు చేస్తుంది.',
    farmLocation: 'పొలం స్థానం',
    useGps: 'నా GPS స్థానాన్ని ఉపయోగించండి',
    orEnterManually: 'లేదా మాన్యువల్‌గా నమోదు చేయండి',
    latitude: 'అక్షాంశం',
    longitude: 'రేఖాంశం',
    farmConditions: 'పొలం పరిస్థితులు',
    waterAvailability: 'నీటి లభ్యత',
    veryLimited: 'చాలా తక్కువ',
    limited: 'తక్కువ',
    moderate: 'మధ్యస్థం',
    good: 'మంచిది',
    abundant: 'సమృద్ధిగా',
    rainfedOnly: 'వర్షాధార',
    irrigationMethod: 'నీటిపారుదల విధానం',
    drip: 'డ్రిప్',
    sprinkler: 'స్ప్రింక్లర్',
    flood: 'వరద పద్ధతి',
    furrow: 'కాలువ పద్ధతి',
    rainfed: 'వర్షాధార',
    otherMethod: 'ఇతర',
    getCropRecButton: 'పంట సిఫార్సులను పొందండి',
    analyzingFarm: 'HARVEX మీ పొలాన్ని విశ్లేషిస్తోంది',
    locationReceived: 'స్థానం స్వీకరించబడింది',
    conditionsLoaded: 'పొలం పరిస్థితులు లోడ్ అయ్యాయి',
    weatherChecked: 'వాతావరణం తనిఖీ చేయబడింది',
    soilChecked: 'నేల సమాచారం తనిఖీ చేయబడింది',
    aiResearching: 'AI అనుకూల పంటలను పరిశోధిస్తోంది',
    rankingCrops: 'అనుకూల పంటలను ర్యాంక్ చేస్తోంది',
    analysisComplete: 'విశ్లేషణ పూర్తయింది',
    pleaseWait: 'HARVEX మీ పొలం పరిస్థితులను అనుకూల పంటలతో పోల్చే వరకు దయచేసి వేచి ఉండండి.',
    examiningCrop: 'HARVEX మీ పంటను పరిశీలిస్తోంది',
    imageUploaded: 'చిత్రం అప్‌లోడ్ చేయబడింది',
    qualityChecked: 'చిత్ర నాణ్యత తనిఖీ చేయబడింది',
    aiExamining: 'AI కనిపించే లక్షణాలను పరిశీలిస్తోంది',
    identifyingCondition: 'సాధ్యమైన పంట పరిస్థితిని గుర్తిస్తోంది',
    preparingExplanation: 'వివరణ సిద్ధం చేస్తోంది',
    suitabilityScore: 'అనుకూలత స్కోర్',
    whyRecommendedShort: 'ఎందుకు సిఫార్సు చేయబడింది',
    soilCompatibility: 'నేల అనుకూలత',
    climateCompatibility: 'వాతావరణ అనుకూలత',
    waterCompatibility: 'నీటి అనుకూలత',
    seasonSuitability: 'సీజన్ అనుకూలత',
    locationSuitability: 'స్థాన అనుకూలత',
    irrigationCompatibility: 'నీటిపారుదల అనుకూలత',
    dataSource: 'డేటా మూలం',
    estimated: 'అంచనా',
    measured: 'కొలిచిన',
    farmerProvided: 'రైతు అందించిన',
    unavailable: 'అందుబాటులో లేదు',
    viewDetails: 'వివరాలు చూడండి',
    collapseDetails: 'వివరాలు మూసివేయండి',
    aiVisualAssessment: 'AI దృశ్య మూల్యాంకనం',
    healthGuidance: 'ఆరోగ్య మార్గదర్శకత్వం',
    treatmentGuidance: 'చికిత్స మార్గదర్శకత్వం',
    immediateActions: 'తక్షణ చర్యలు',
    culturalPractices: 'సాంస్కృతిక/సేంద్రియ పద్ధతులు',
    chemicalControl: 'రసాయన నియంత్రణ',
    safetyNote: 'భద్రతా గమనిక',
    followUpIn: 'ఫాలో-అప్ సిఫార్సు చేయబడింది',
    routineCheck: 'తదుపరి రొటీన్ తనిఖీ',
    days: 'రోజులు',
    imageQualityGuidance: 'చిత్ర నాణ్యత మార్గదర్శకత్వం',
    nextSteps: 'తదుపరి దశలు',
    tryAgainIn: 'మళ్ళీ ప్రయత్నించండి',
    clearerImage: 'స్పష్టమైన చిత్రంతో',
    followUpRecommended: 'ఫాలో-అప్ సిఫార్సు చేయబడింది',
    uploadAnother: 'తదుపరి కొన్ని రోజుల్లో మొక్క పరిస్థితిని తిరిగి అంచనా వేయడానికి మరొక చిత్రాన్ని అప్‌లోడ్ చేయండి.',
    aiUnavailableTitle: 'AI విశ్లేషణ తాత్కాలికంగా అందుబాటులో లేదు',
    nvidiaUnavailableDesc: 'NVIDIA Vision AI తాత్కాలికంగా అందుబాటులో లేదు. దయచేసి తర్వాత మళ్ళీ ప్రయత్నించండి. మీ అప్‌లోడ్ చేసిన చిత్రం రోగ నిర్ధారణగా మార్చబడలేదు.',
    detectionNotAvailable: 'గుర్తింపు అందుబాటులో లేదు',
    tipClearPhoto: 'టిప్: స్పష్టమైన, కాంతి గల ఆకు దగ్గరి ఫోటో ఉపయోగించండి.',
    noDiseaseFound: 'వ్యాధి కనుగొనబడలేదు',
    provider: 'ప్రొవైడర్',
    model: 'మోడల్',
    severeSeverity: 'తీవ్రమైన',
    moderateSeverity: 'మధ్యస్థం',
    mildSeverity: 'తేలికపాటి',
    noneSeverity: 'లేదు',
    funLoadingNote1: 'మీ నేలకు పొరుగు కంటే ఎక్కువ ఆశయం ఉందో లేదో చూస్తోంది...',
    funLoadingNote2: 'పంట మార్పిడిపై ఆవుల అభిప్రాయం అడుగుతోంది...',
    funLoadingNote3: 'గరిష్ట సంతోషం కోసం ఎన్ని పొద్దుతిరుగుడు పూలు నాటాలో లెక్కిస్తోంది...',
    funLoadingNote4: 'ప్రాచీన వ్యవసాయ పంచాంగాలతో సరిపోల్చుతోంది...',
    funLoadingNote5: 'మీ పంట పెరగడానికి కూడా ఎక్కువ సమయం పడుతుంది! ఓపిక పట్టండి, రైతు...',
    funLoadingNote6: 'AI నాటు సలహా కోసం చంద్రుడిని అడుగుతోంది...',
    funLoadingNote7: 'కోడి ఈ సిఫార్సుతో ఏకీభవిస్తుందో లేదో చూస్తోంది...',
    funLoadingNote8: 'మీ భవిష్యత్ కోత రుచి కోసం ఆప్టిమైజ్ చేస్తోంది...',
    funDiseaseNote1: 'మీ ఆకును చాలా జాగ్రత్తగా చూస్తోంది...',
    funDiseaseNote2: 'మొక్క వైద్యుడి నుండి రెండవ అభిప్రాయం అడుగుతోంది...',
    funDiseaseNote3: 'AI మీ ఆకును చాలా గట్టిగా చూస్తోంది...',
    funDiseaseNote4: 'వైద్యులకు కూడా X-రే చదవడానికి సమయం పడుతుంది! రిలాక్స్...',
    funDiseaseNote5: 'మీ ఆకును 10,000 ఆరోగ్యకరమైన ఆకులతో పోల్చుతోంది...',
    loadingInsights: 'అంతర్దృష్టులు లోడ్ అవుతున్నాయి...',
    generatingInsights: 'అంతర్దృష్టులు రూపొందిస్తోంది...',
    noInsightsData: 'ఇంకా తగినంత పొలం డేటా లేదు',
    noInsightsDataDesc: 'AI-ఆధారిత అంతర్దృష్టులు పొందడానికి ఖర్చులు, కోతలు లేదా పంట సమాచారం జోడించండి.',
    insightsUnavailable: 'పొలం అంతర్దృష్టులు తాత్కాలికంగా అందుబాటులో లేవు.',
    insightsUnavailableDesc: 'AI సేవ ప్రస్తుతం అంతర్దృష్టులను రూపొందించలేకపోయింది.',
    noActiveCropInsights: 'ప్రస్తుతం పంట లేదు',
    noActiveCropInsightsDesc: 'AI-ఆధారిత పొలం అంతర్దృష్టులు పొందడానికి పంట ప్రారంభించండి.',
    aiSummary: 'AI సారాంశం',
    refreshInsights: 'అంతర్దృష్టులు రిఫ్రెష్ చేయండి',
    resultAvailable: 'ఫలితం అందుబాటులో ఉంది',
    viewResult: 'ఫలితం చూడండి',
    resultUnavailable: 'ఈ సిఫార్సును లోడ్ చేయడం సాధ్యం కాలేదు.',
    cropRecommendationResult: 'పంట సిఫార్సు',
    riskAnalysisResult: 'ప్రమాద విశ్లేషణ',
    irrigationAdviceResult: 'నీటిపారుదల సలహా',
    financialAnalysisResult: 'ఆర్థిక విశ్లేషణ',
    farmInsightsResult: 'పొలం అంతర్దృష్టులు',
    majorRisks: 'ముఖ్యమైన ప్రమాదాలు',
    overallRisk: 'మొత్తం ప్రమాదం',
    keyConcerns: 'ముఖ్య ఆందోళనలు',
    urgentActions: 'తక్షణ చర్యలు',
    irrigationRecommendation: 'సిఫార్సు',
    farmSummary: 'పొలం సారాంశం',
    totalExpensesLabel: 'మొత్తం ఖర్చులు',
    totalRevenueLabel: 'మొత్తం ఆదాయం',
    harvestCount: 'కోత సంఖ్య',
    insightCategory: 'వర్గం',
    insightPriority: 'ప్రాధాన్యత',
    insightSource: 'మూలం',
    close: 'మూసివేయండి',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const { user, updateUser } = useAuth();
  const [language, setLanguageState] = useState<Language>(() => {
    if (user?.preferred_language === 'te') return 'te';
    return 'en';
  });

  useEffect(() => {
    if (user?.preferred_language && user.preferred_language !== language) {
      setLanguageState(user.preferred_language as Language);
    }
  }, [user?.preferred_language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (user) {
      updateUser({ preferred_language: lang }).catch(() => {});
    }
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
